# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Vos
description: > 
  Chris Vos - Mathematician, student at Utrecht University specializing in (unstable, synethetic, computational) homotopy theory and music producer making electronic and pop music.
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://chrisvos.net/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

navigation:
  - text: home
    url: /
  - text: math
    url: /math
  - text: music
    url: /music
  - text: projects
    url: /projects

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
