# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Vos
description: > 
  The portofolio website of Chris Vos, displaying all 
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://chrisvos.net/  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

navigation:
  - text: Home
    url: /
  - text: Discography
    url: /discography
  - text: Live
    url: /live
  - text: Teaching
    url: /teaching
  - text: Other 
    url: /electronics

# Plugins
gems:
  - jekyll-seo-tag
